### ISSUE TITLE
TypeError: ctx is undefined

### ISSUE THREAD

**Issue by salmansheri** [clerkinc/clerk-next-app-router-starter#3] opened 2023-06-20 18:00 UTC
![clerk](https://github.com/clerkinc/clerk-next-app-router-starter/assets/95226945/61bbd516-31bb-4c3d-a629-49ef64c2c5e2)
![terminal](https://github.com/clerkinc/clerk-next-app-router-starter/assets/95226945/028509dc-4de3-43ce-a6c4-91bfe2477aae)

i am getting this error in my project please help me solve it

**Comment by yasyaindra** [comment] 2023-08-06 02:23
Make sure to wrap html and body in `<ClerkProvider>`
```tsx
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
```
at layout.tsx

**Comment by magnusriga** [comment] 2023-09-10 13:07
I am getting the same error when trying to access the `sign-in` route. I already wrapped the app in `ClerkProvider`. Any idea @yasyaindra ?

**Comment by magnusriga** [comment] 2023-09-10 14:26
I fixed it. My issue was related to what you said @yasyaindra . I had wrapped a lower-level route with the `ClerkProvider`. If others experience a similar issue, try to move the provider right outside the html tag in the outermost `layout.js`.

**Comment by LekoArts** [comment] 2023-10-16 09:50
I'm closing this as it's a user error and not a bug inside this repository.

**Closed as not planned by LekoArts** 2023-10-16 09:50 UTC
